parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: sfHello
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 3a78f52363b05745414a9e7cc6fa9dd25e6d605c
    database_path: null
