<?php

namespace Genemu\Bundle\FormBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ImageController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Genemu\Bundle\FormBundle\Controller\ImageController();
        return $instance;
    }
}
